# Generated by Django 3.1.5 on 2021-01-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0008_libro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
